apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-recipe-parser-deployment
  namespace: insta-parser
  labels:
    app: instagram-recipe-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instagram-recipe-parser
  template:
    metadata:
      labels:
        app: instagram-recipe-parser
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: instagram-recipe-parser
        image: 135234974038.dkr.ecr.us-east-1.amazonaws.com/instagram_recipe_parser:a619f91
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: OPENAI_API_KEY
          value: dummy
        - name: ALLOWED_EMAILS
          value: "dummy"
      nodeSelector:
        kubernetes.io/os: linux