apiVersion: v1
kind: Service
metadata:
  name: instagram-recipe-parser-service
  namespace: insta-parser
  labels:
    app: instagram-recipe-parser
spec:
  selector:
    app: instagram-recipe-parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080